---
pipeline:
 - docs_unit
 - dw_unit
 - site_unit
 - site_integration
 - site_integration_predix_ui

edges:
 - site_unit: docs_unit
 - site_unit: dw_unit
 - site_unit: site_integration
 - site_integration: site_integration_predix_ui

profiles:
  site_unit:
    script: ./scripts/unit_test.sh
    profile_config:
      advance_on:                   # can also just be string value
        - branch: "*"
          advance_on: "always"

 # Integration tests for services/site
  site_integration:
    script: ./scripts/deploy.sh
    profile_config:
      advance_on:                   # can also just be string value
        - branch: "*"
          advance_on: "always"

 # --------------------------
 # Site Integration (Predix)
 # --------------------------
  site_integration_predix_ui:
    script: ./scripts/deploy.sh

  dw_unit:
     script: ./scripts/deploy.sh
  
 # --------------------------
 # Worker unit tests
 # --------------------------
  docs_unit:
     script: ./scripts/deploy.sh

  default:
    script: dev/null

